# Generated by Django 4.1.1 on 2022-10-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('dp', models.ImageField(default='images/defaults/dp.png', upload_to='images/dps/')),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7)),
                ('bday', models.DateField(blank=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to='accounts.profile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
