# Generated by Django 4.1.1 on 2022-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_bday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
