# Generated by Django 4.1.1 on 2022-10-09 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/entries/')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('content', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('edited', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=60)),
                ('done', models.BooleanField(default=False)),
                ('entries', models.ManyToManyField(blank=True, related_name='groupings', to='main.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
